// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bg-patterns/Hexagons.tsx": () => import("../components/mockups/bg-patterns/Hexagons.tsx"),
  "./components/mockups/bg-patterns/Lattice.tsx": () => import("../components/mockups/bg-patterns/Lattice.tsx"),
  "./components/mockups/bg-patterns/MaroonCarbon.tsx": () => import("../components/mockups/bg-patterns/MaroonCarbon.tsx"),
  "./components/mockups/bg-patterns/NeonPentagons.tsx": () => import("../components/mockups/bg-patterns/NeonPentagons.tsx"),
  "./components/mockups/bg-patterns/RedNeonWave.tsx": () => import("../components/mockups/bg-patterns/RedNeonWave.tsx"),
  "./components/mockups/bg-patterns/StoneCubes.tsx": () => import("../components/mockups/bg-patterns/StoneCubes.tsx"),
  "./components/mockups/bg-patterns/TealSmoky.tsx": () => import("../components/mockups/bg-patterns/TealSmoky.tsx"),
  "./components/mockups/bg-patterns/Topographic.tsx": () => import("../components/mockups/bg-patterns/Topographic.tsx")
};
